spring.datasource.url= jdbc:mysql://Localhost:3306/investmentdb?useSSL=false
spring.datasource.username= root
spring.datasource.password= Gptw#369


#spring.datasource.url= jdbc:mysql://sql6.freesqldatabase.com:3306/sql6682230?useSSL=false
#spring.datasource.username= sql6682230
#spring.datasource.password= 1idNeh9g6g
#
#spring.datasource.url= jdbc:mysql://bklakj19gr2ia3o3nulr-mysql.services.clever-cloud.com:3306/bklakj19gr2ia3o3nulr
#spring.datasource.username= uljf4pbzhvvy7mtu
#spring.datasource.password= pHekSG9ilt02dMMWleTA

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql = true
server.port = 8085

#Host: sql6.freesqldatabase.com
#Database name: sql6682230
#Database user: sql6682230
#Database password: 1idNeh9g6g
#Port number: 3306

#ACk1ZTc-JW9oyr5abu7AfA

#postgresql://kapil:ACk1ZTc-JW9oyr5abu7AfA@tamer-markhor-4258.g95.gcp-us-west2.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full